### ISSUE TITLE
Orleans run with docker => unexpected direct silo connection on proxy endpoint from

### ISSUE THREAD

**Issue by youlxs** [dotnet/orleans#6895]
I can not understand why orlean runs with docker, and I can't use the default docker network bridge settting.
If I use the virtual ip generated by the default bridge network, the client can't connect to the host though the host ip.
In this case I need bind the host ip to the silo host in the docker env.

 Closing connection with remote endpoint 172.17.0.1:60460. Exception: System.InvalidOperationException: Unexpected direct silo connection on proxy endpoint from S172.17.0.2:2000:348652524

![image](https://user-images.githubusercontent.com/10609666/104887592-7e19df00-59a6-11eb-8f93-69437fd740bf.png)

**Comment by ReubenBond** [comment]
How have you configured it?

**Comment by ScarletKuro** [comment]
I have the exactly same problem. I have looked at this issue https://github.com/dotnet/orleans/issues/6420 and it doesn't have an answer.
I'm hosting the silo on Kubernetes.
I have used this documentation https://dotnet.github.io/orleans/docs/deployment/kubernetes.html
and this example https://github.com/ReubenBond/hanbaobao-web
so my only silo settings are
```
            siloBuilder
                .UseKubernetesHosting()
                .UseRedisClustering(options => options.ConnectionString = $"{Environment.GetEnvironmentVariable("REDIS")}:6379")
                .ConfigureApplicationParts(parts =>
                {
                    parts.AddFromApplicationBaseDirectory();
                })
                .UseLinuxEnvironmentStatistics()
                .UseDashboard();
```
The silo is working just fine, I can even open the dashboard and see everything what is happening and that silo is up.
Now i want to connect to the silo **OUTSIDE** of k8 using IClusterClient and I have tried UseStaticClustering and i can see in dashboard that the client is connected but then immediately rejected with error `Closing connection with remote endpoint host:port. Exception: System.InvalidOperationException: Unexpected direct silo connection on proxy endpoint from`.
Then i tried to use UseRedisClustering in my client and it gives me `Unable to connect to endpoint Sxx.xxx.xxx.x:30000`

The question is: how do i connect to orleans outside of k8 with the client?
I'm not satisfied with answer
> If you set a public IP for orlean cluster and connect your client with this IP over internet, this is not proper architecture.
Because I have an WPF client that i want connect to orleans server.

**Comment by ReubenBond** [comment]
@ScarletKuro 
It looks like in the first case you were using static clustering and possibly setting the incorrect port.

In the second case, your Redis cluster is not available outside of the Kubernetes cluster.

Running Orleans in Kubernetes and then trying to connect from outside of Kubernetes is going to be tricky. How are you configuring that? Your WPF app needs some mechanism to connect directly to each of the Orleans pods.

Theoretically, you could create a load-balanced service in Kubernetes which connected you to one of the gateways and used static clustering, pointing it at your cluster ip and the port your service exposes. That should work, too.

Disclaimer: exposing an Orleans service directly to the internet is dangerous, especially without configuring mutual TLS. I do not recommend it. In your case, I assume your clients are trusted and your networks are secure.

**Comment by ScarletKuro** [comment]
> In the second case, your Redis cluster is not available outside of the Kubernetes cluster.

It is.
![redis](https://i.imgur.com/Eg24bGG.png)

> Disclaimer: exposing an Orleans service directly to the internet is dangerous, especially without configuring mutual TLS. I do not recommend it. In your case, I assume your clients are trusted and your networks are secure.

It will be used in internal network only, so we do not care about the security in this case.

> The documentation doesn't talk about it because exposing Orleans to an unsecured network is not recommended

I have an question then, how people suppose to make an dev/test environment for example, where they want to host silo on k8 and work with siloclient on their machine.
Also, as i see I'm not alone in this problem.


This is my whole k8 configuration(except ServiceAccount)
<details>
  <summary>This is my silo deployment</summary>

  ```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiisu-gateway
  labels:
    orleans/serviceId: kiisu-gateway
spec:
  selector:
    matchLabels:
      orleans/serviceId: kiisu-gateway
      app: kiisu-gateway
  replicas: 1
  template:
    metadata:
      labels:
        # This label is used to identify the service to Orleans
        orleans/serviceId: kiisu-gateway
        # This label is used to identify an instance of a cluster to Orleans.
        # Typically, this will be the same value as the previous label, or any 
        # fixed value.
        # In cases where you are not using rolling deployments (for example,
        # blue/green deployments),
        # this value can allow for distinct clusters which do not communicate
        # directly with each others,
        # but which still share the same storage and other resources.
        orleans/clusterId: kiisu-gateway
        app: kiisu-gateway
    spec:
      containers:
        - name: main
          image: docker.fleet.zone/winpos-integrations/kiisu-gateway:010187e2665a9a736aa56d4c725dc6a6e5a1284a
          imagePullPolicy: Always
          ports:
          # Define the ports which Orleans uses
          - containerPort: 11111
          - containerPort: 30000
          - containerPort: 80
          - containerPort: 443
          resources:
            limits:
              memory: 512Mi
          env:
          # The Azure Storage connection string for clustering is injected as an
          # environment variable
          # It must be created separately using a command such as:
          # > kubectl create secret generic az-storage-acct `
          #     --from-file=key=./az-storage-acct.txt
          #- name: STORAGE_CONNECTION_STRING
          #  valueFrom:
          #    secretKeyRef:
          #      name: az-storage-acct
          #      key: key
          # Configure settings to let Orleans know which cluster it belongs to
          # and which pod it is running in
          - name: ORLEANS_SERVICE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/serviceId']
          - name: ORLEANS_CLUSTER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/clusterId']
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
            value: "120"
          - name: REDIS
            value: "redis" # The name of the redis service defined above
          request:
            # Set resource requests
      terminationGracePeriodSeconds: 180
      #imagePullSecrets:
      #  - name: my-image-pull-secret
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  ```
</details>

<details>
  <summary>Silo service</summary>

  ```
  kind: Service
apiVersion: v1
metadata:
  name: kiisu-gateway
spec:
  selector:
    app: kiisu-gateway
  type: NodePort
  ports:
  - port: 80
  selector: kiisu-gateway
  - name: port-11111
    protocol: TCP
    port: 11111
    targetPort: 11111
  - name: port-30000
    protocol: TCP
    port: 30000
    targetPort: 30000
  - name: port-443
    protocol: TCP
    port: 443
    targetPort: 443
  ```
</details>
<details>
  <summary>Redis deployment</summary>

  ```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
  ```
</details>
<details>
  <summary>redis service</summary>

  ```
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    app: redis
  ```
</details>

> Theoretically, you could create a load-balanced service in Kubernetes which connected you to one of the gateways and used static clustering, pointing it at your cluster ip and the port your service exposes. That should work, too.

Can you give at least rough example?
