### ISSUE TITLE
k8s cluster: Silo requests got rejected after the silo restarted from "I have been told I am dead" in MembershipTableManager

### ISSUE THREAD

**Issue by shykln** [dotnet/orleans#7654]
Hi Team,

I found that when a silo restarted (by k8s) from a previous process termination (with same pod/host name and ip address), other silos will rejected messages from this known-dead silo. And I can see 2 records in the membership table with same Hostname and Ipaddress. 1 record shows status 3(running) and the the other record shows status 6(dead).

Environment:

1. Silo hosts are hosted in a k8s cluster. 8 silos(pods) are in my Orleans cluster.
2. I use ```mysql``` for orleans persistence (Please note that there is a warning shown in the console: ```CleanupDefunctSiloEntries operation is not supported by the current implementation of IMembershipTable. Disabling the timer now.```) I think it is not implemented in Orleans mysql persistence library.

Issue:

1. One silo (192.168.199.100) was experiencing network issue, other silos could not connect to it:
```
{ 
   @i: 3b21fc3b
   @l: Warning
   @m: Exception while processing messages from remote endpoint "192.168.199.100:11111"
   @t: 2022-03-24T13:49:02.3909658Z
   @x: Microsoft.AspNetCore.Connections.ConnectionResetException: Connection reset by peer ---> System.Net.Sockets.SocketException (104): Connection reset by peer at Orleans.Networking.Shared.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e) in /_/src/Orleans.Core/Networking/Shared/SocketAwaitableEventArgs.cs:line 42 at Orleans.Networking.Shared.SocketAwaitableEventArgs.GetResult() in /_/src/Orleans.Core/Networking/Shared/SocketAwaitableEventArgs.cs:line 31 at Orleans.Networking.Shared.SocketConnection.ProcessReceives() in /_/src/Orleans.Core/Networking/Shared/SocketConnection.cs:line 191 at Orleans.Networking.Shared.SocketConnection.DoReceive() in /_/src/Orleans.Core/Networking/Shared/SocketConnection.cs:line 135 --- End of inner exception stack trace --- at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result) at System.IO.Pipelines.Pipe.GetReadAsyncResult() at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /_/src/Orleans.Core/Networking/Connection.cs:line 348

   EndPoint: 192.168.199.100:11111
   LocalEndPoint: 192.168.213.171:59548
   RemoteEndPoint: 192.168.199.100:11111
   SourceContext: Orleans.Networking
   }
}
```
2. Other silos suspected that 192.168.199.100 is dead. And they write down this in the Membership table.
3. When 192.168.199.100 is back online, it found that it is declared to be known-dead.
```
log: Process terminated. FATAL EXCEPTION from Orleans.Runtime.MembershipService.MembershipTableManager. Context: I have been told I am dead, so this silo will stop! I should be Dead according to membership table (in CleanupTableEntries): entry = [SiloAddress=S192.168.199.100:11111:385796545 SiloName=xxxxx Status=Dead HostName=xxxxxxxx ProxyPort=30000 RoleName= UpdateZone=0 FaultZone=0 StartTime = 2022-03-24 05:42:26.000 GMT IAmAliveTime = 2022-03-24 13:47:34.000 GMT Suspecters = [S192.168.213.171:11111:385796545, S192.168.225.63:11111:385796535] SuspectTimes = [2022-03-24 13:48:52.934 GMT, 2022-03-24 13:48:56.197 GMT]].. Exception: null. 
}

```
4. When 192.168.199.100 terminated itself, K8S will restart the pod(silo). This is a behaviour of k8s. 
5. When 192.168.199.100 restarted, I can see 2 records in the membership table with same Hostname and Ipaddress. 1 record shows status 3(running) and the the other record shows status 6(dead).
6. 192.168.199.100 somehow gets Reminder grain activations in itself and started to deliver Reminder's ReceiveReminder() call. But its grain calls are rejected by other silos and it could not get response until grain msg timeout exceptions are thrown. And this silo never get recovered from this fault running status.
```
Silo "S192.168.213.171:11111:385796545" is rejecting message to known-dead silo "S192.168.199.100:11111:385796545": "Request S192.168.213.171:11111:385796545*stg/ClientObserverRegistrar/0000000d@S0000000d->S192.168.199.100:11111:385796545*stg/DirectoryService/0000000a@S0000000a InvokeMethodRequest Orleans.Runtime.IRemoteGrainDirectory:RegisterAsync #331601"
```
```
System.TimeoutException: Response did not arrive on time in 00:03:30 for message: Request S192.168.199.100:11111:385825746*stg/Orleans.Runtime.ReminderService.LocalReminderService/00000000@S00000000->S192.168.41.228:11111:385796535*grn.......
```

Please kindly advise if 
1. this situation could be avoided by configuration. 
2. Or is it related to "CleanupDefunctSiloEntries operation is not supported by the current implementation of IMembershipTable" in ```orleans mysql persistence library```. 
3. Or is it because that ```Microsoft.Orleans.Hosting.Kubernetes``` is always using the same silo hostname so that when a silo is restarted, 2 silo records with the same silo host name got stored in the membership table(status = 3(running) & 6(dead)).

Thank you very much.

**Comment by ReubenBond** [comment]
If silos can't connect to each other, they'll start voting each other dead, that much is expected. Are you able to share full logs? Given you're using `UseKubernetesHosting`, please also share your k8s deployment yaml

**Comment by shykln** [comment]
Hi @ReubenBond ,

Sorry I could not share the logs. 
k8s yaml:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: $orleans-service
  name: $orleans-service
  namespace: $NAMESPACE
spec:
  ports:
  - port: 80
    name: web
  - port: 30000
    name: gateway
  - port: 11111
    name: silo
  selector:
    app: $orleans
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: $orleans
  name: $orleans
  namespace: $NAMESPACE
spec:
  replicas: $replica
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: $orleans
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: $orleans
        orleans/serviceId: my-distributed-svc
        orleans/clusterId: my-cluster
    spec:
      containers:
      - name: $orleans
        image: $REGISTRY_URL/$orleans:$IMAGETAG
        resources:
          limits:
            cpu: 1000m
            memory: 1536Mi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: $APPENV
        - name: POD_NAME
          value: $orleans
        - name: POD_NAMESPACE
          value: $NAMESPACE
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ORLEANS_SERVICE_ID
          value: my-distributed-svc
        - name: ORLEANS_CLUSTER_ID
          value: my-cluster
        - name: CodeVersion
          value: $V_CodeVersion
        - name: AppName
          value: my-orleans
        ports:
        - containerPort: 80
        - containerPort: 30000
        - containerPort: 11111
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null

status: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    kubernetes.io/ingress.allow-http: 'true'
  generation: 1
  name: $orleans-service-ingress
  namespace: $NAMESPACE
spec:
  rules:
  - host: $ENGINE_DASHBOARD_HOST
    http:
      paths:
        - path: /
          backend:
            serviceName: $orleans-service
            servicePort: 80
  tls:
  - hosts:
    - $ENGINE_DASHBOARD_HOST
    secretName: wildcard-tesla-cn-tls
```
