### ISSUE TITLE
K8s monitoring problem: The response ended prematurely while waiting for the next frame from the server.

### ISSUE THREAD

**Issue by freever** [dotnet/orleans#7672]
Hi guys

I've really been battling with this one for a while and just can't seem to get rid of it. I have a Cluster with one pod running in Kubernetes using the KubernetesHosting package (I am not using the Kubernetes Hosting package). 

Every ten minutes, regular as clockwork, I get this error:

> [15:20:55.849 ERR[] Error monitoring Kubernetes pods
System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|57_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at k8s.LineSeparatedHttpContent.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.Watcher`1.<>c.<CreateWatchEventEnumerator>b__21_1[TR[](Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Orleans.Hosting.Kubernetes.KubernetesClientExtensions.WatchAsync[TList,TValue[](HttpOperationResponse`1 watchList, CancellationToken cancellation)+MoveNext() in /_/src/Orleans.Hosting.Kubernetes/KubernetesClientExtensions.cs:line 65
   at Orleans.Hosting.Kubernetes.KubernetesClientExtensions.WatchAsync[TList,TValue[](HttpOperationResponse`1 watchList, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Orleans.Hosting.Kubernetes.KubernetesClusterAgent.MonitorKubernetesPods() in /_/src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs:line 224
   at Orleans.Hosting.Kubernetes.KubernetesClusterAgent.MonitorKubernetesPods() in /_/src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs:line 224

The cluster works and services requests from the outside, but this error presumably means that the cluster won't be managed correctly. 

I have followed the documentation as closely as possible. 

The yaml for my deployment looks like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mb-api
  labels: 
    orleans/serviceId: deploy-mb-api 
spec:
  replicas: 1
  selector:
    matchLabels:
      orleans/serviceId: deploy-mb-api
      app: mb-api  
  minReadySeconds: 20   
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1     
  template:
    metadata:
      labels:
        app: mb-api
        orleans/serviceId: deploy-mb-api
        orleans/clusterId: deploy-mb-api
    spec:
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
      - name: secret-docker-auth
      containers:
      - name: container-mb-api
        image: freever/mb-api:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /podhealth
            port: 7100
          initialDelaySeconds: 0
          periodSeconds: 120
          timeoutSeconds: 1
          failureThreshold: 3
        ports: 
        - containerPort: 7100 
        - containerPort: 8000 
        - containerPort: 11111
        - containerPort: 30000
        env:  
        - name: ORLEANS_SERVICE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['orleans/serviceId']
        - name: ORLEANS_CLUSTER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['orleans/clusterId']
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

At startup the pod has the correct environment variables:

> ORLEANS_CLUSTER_ID: deploy-mb-api
ORLEANS_SERVICE_ID: deploy-mb-api
POD_IP: 10.2.3.197
POD_NAME: deploy-mb-api-596c688598-jrjz4
POD_NAMESPACE: default

The cluster is RBAC-enabled and I have added the Role and RoleBinding specified in the docs. 

My K8s cluster also has ingress set up with a service configured to reach the cluster as follows:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: service-mb-api
spec:
  type: ClusterIP             
  ports:
    - port: 7100              
      targetPort: 7100       
  selector:
    app: mb-api      
```

Prior to using the Kubernetes Hosting I was just using the mb-app label as a selector to route requests from the service to the pods running Orleans - should I still be doing this now that there is the app label and selector configured using orleans/serviceId? 

Any advice, tips, thoughts and/or prayers appreciated.
