### ISSUE TITLE
why orleans app is patching the clusterId pod label and modifying it?

### ISSUE THREAD

**Issue by dima-sh-papaya** [dotnet/orleans#9365]
Hi, I'm possibly missing something basic, but I've read [this doc](https://learn.microsoft.com/en-us/dotnet/orleans/deployment/kubernetes), and it does not mention that an Orleans based app will be patching or modifying anything in Kubernetes cluster. 
The behavior I'm observing is: 

I'm setting the labels serviceId and clusterId as mentioned in the docs, to a simple name like "myapp". Starting the application in a "deployment", the app starts and modifies the label clusterId to be something like "myapp_cluster_my-eks-environment" which makes the pod escape from 'deployment' by that labels don't match it anymore, and deployment controller spawns new pod with 'correct labels' , causing infinite loop of spawning more containers. 

My question is, why does the app modify the pod labels? Isn't it supposed to use label as source of truth?

We set env vars as in documentation, with: 
```
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['orleans/clusterId']
```

all I can understand from the 'new name' it gives to the label is that it uses ASPNETCORE_ENVIRONMENT as a suffix (it matches the suffix it uses of my eks env name). 

Why does this happen and how is it possible to fix it? am I missing something basic from the docs, could someone point me in the right direction please? 🙏
